-- code_master
INSERT INTO code_master VALUES('ARE','지역');
INSERT INTO code_master VALUES('SEG','세그먼트');
INSERT INTO code_master VALUES('FUL','연료');
INSERT INTO code_master VALUES('MSS','기어');
INSERT INTO code_master VALUES('CST','차 상태');
INSERT INTO code_master VALUES('RTP','렌트 타입');
INSERT INTO code_master VALUES('RST','렌트 상태');
INSERT INTO code_master VALUES('MAT','회원 권한');
INSERT INTO code_master VALUES('MST','회원 상태');
INSERT INTO code_master VALUES('MDR','회원 탈퇴 사유');
INSERT INTO code_master VALUES('PST','업체 상태');
INSERT INTO code_master VALUES('FTP','파일 타입');
INSERT INTO code_master VALUES('DBR','신고 사유');
INSERT INTO code_master VALUES('RBT','건의 분류');
INSERT INTO code_master VALUES('QST','QNA 상태');
INSERT INTO code_master VALUES('COP', '차량 옵션');
INSERT INTO code_master VALUES('IOP', '보험 옵션');
INSERT INTO code_master VALUES('ITO', '캠핑용품 옵션');

--code_sub
INSERT INTO code_sub VALUES('ARE01','서울','ARE');
INSERT INTO code_sub VALUES('ARE02','경기','ARE');
INSERT INTO code_sub VALUES('ARE03','인천','ARE');
INSERT INTO code_sub VALUES('ARE04','강원','ARE');
INSERT INTO code_sub VALUES('ARE05','세종','ARE');
INSERT INTO code_sub VALUES('ARE06','대전','ARE');
INSERT INTO code_sub VALUES('ARE07','충남','ARE');
INSERT INTO code_sub VALUES('ARE08','충북','ARE');
INSERT INTO code_sub VALUES('ARE09','부산','ARE');
INSERT INTO code_sub VALUES('ARE10','울산','ARE');
INSERT INTO code_sub VALUES('ARE11','경남','ARE');
INSERT INTO code_sub VALUES('ARE12','대구','ARE');
INSERT INTO code_sub VALUES('ARE13','경북','ARE');
INSERT INTO code_sub VALUES('ARE14','광주','ARE');
INSERT INTO code_sub VALUES('ARE15','전남','ARE');
INSERT INTO code_sub VALUES('ARE16','전북','ARE');
INSERT INTO code_sub VALUES('ARE17','제주','ARE');

INSERT INTO code_sub VALUES('SEG01', '경차', 'SEG');
INSERT INTO code_sub VALUES('SEG02', '소형차', 'SEG');
INSERT INTO code_sub VALUES('SEG03', '준중형차', 'SEG');
INSERT INTO code_sub VALUES('SEG04', '중형차', 'SEG');
INSERT INTO code_sub VALUES('SEG05', '대형차', 'SEG');
INSERT INTO code_sub VALUES('SEG06', '스포츠카', 'SEG');
INSERT INTO code_sub VALUES('SEG07', 'SUV', 'SEG');
INSERT INTO code_sub VALUES('SEG08', '기타', 'SEG');

INSERT INTO code_sub VALUES('FUL01', '가솔린', 'FUL');
INSERT INTO code_sub VALUES('FUL02', '디젤', 'FUL');
INSERT INTO code_sub VALUES('FUL03', '하이브리드', 'FUL');
INSERT INTO code_sub VALUES('FUL04', '전기', 'FUL');

INSERT INTO code_sub VALUES('MSS01', '수동', 'MSS');
INSERT INTO code_sub VALUES('MSS02', '자동', 'MSS');

INSERT INTO code_sub VALUES('CST01', '대기', 'CST');
INSERT INTO code_sub VALUES('CST02', '사용', 'CST');
INSERT INTO code_sub VALUES('CST03', '수리', 'CST');
INSERT INTO code_sub VALUES('CST04', '삭제', 'CST');

INSERT INTO code_sub VALUES('RTP01', '일반', 'RTP');
INSERT INTO code_sub VALUES('RTP02', '프리미엄', 'RTP');

INSERT INTO code_sub VALUES('RST01', '대기', 'RST');
INSERT INTO code_sub VALUES('RST02', '진행', 'RST');
INSERT INTO code_sub VALUES('RST03', '완료', 'RST');
INSERT INTO code_sub VALUES('RST04', '취소', 'RST');

INSERT INTO code_sub VALUES('MAT01', '관리자', 'MAT');
INSERT INTO code_sub VALUES('MAT02', '업체', 'MAT');
INSERT INTO code_sub VALUES('MAT03', '사용자', 'MAT');

INSERT INTO code_sub VALUES('COP01','크루즈 컨트롤','COP');
INSERT INTO code_sub VALUES('COP02','HUD','COP');
INSERT INTO code_sub VALUES('COP03','전자 주차브레이크','COP');
INSERT INTO code_sub VALUES('COP04','네비게이션','COP');
INSERT INTO code_sub VALUES('COP05','블루투스','COP');
INSERT INTO code_sub VALUES('COP06','CD플레이어','COP');
INSERT INTO code_sub VALUES('COP07','USB단자','COP');
INSERT INTO code_sub VALUES('COP08','AUX단자','COP');
INSERT INTO code_sub VALUES('COP09','열선시트','COP');
INSERT INTO code_sub VALUES('COP10','통풍시트','COP');
INSERT INTO code_sub VALUES('COP11','전자제어 서스펜션','COP');
INSERT INTO code_sub VALUES('COP12','어라운드뷰','COP');
INSERT INTO code_sub VALUES('COP13','후방카메라','COP');
INSERT INTO code_sub VALUES('COP14','ABS','COP');
INSERT INTO code_sub VALUES('COP15','차선이탈 방지','COP');
INSERT INTO code_sub VALUES('COP16','썬루프','COP');
INSERT INTO code_sub VALUES('COP17','LED헤드램프','COP');
INSERT INTO code_sub VALUES('COP18','전동트렁크','COP');
INSERT INTO code_sub VALUES('COP19','루프랙','COP');
INSERT INTO code_sub VALUES('COP20','하이패스','COP');

INSERT INTO code_sub VALUES('IOP01','일반자차','IOP');
INSERT INTO code_sub VALUES('IOP02','완전자차','IOP');

-- brand
INSERT INTO brand_code VALUES('HY', '현대');
INSERT INTO brand_code VALUES('GE', '제네시스');
INSERT INTO brand_code VALUES('KI', '기아');
INSERT INTO brand_code VALUES('CH', '쉐보레');
INSERT INTO brand_code VALUES('SA', '르노삼성');
INSERT INTO brand_code VALUES('SS', '쌍용');
INSERT INTO brand_code VALUES('BM', 'BMW');
INSERT INTO brand_code VALUES('BZ', '벤츠');
INSERT INTO brand_code VALUES('AU', '아우디');
INSERT INTO brand_code VALUES('TE', '테슬라');
INSERT INTO brand_code VALUES('FX', '폭스바겐');
INSERT INTO brand_code VALUES('ET', '기타');

-- model
INSERT INTO model_code VALUES('HYGR', '그렌저', 'HY', '');
INSERT INTO model_code VALUES('HYSN', '쏘나타', 'HY', '');
INSERT INTO model_code VALUES('HYAV', '아반떼', 'HY', '');
INSERT INTO model_code VALUES('HYSF', '산타페', 'HY', '');
INSERT INTO model_code VALUES('HYTS', '투싼', 'HY', '');
INSERT INTO model_code VALUES('HYKN', '코나', 'HY', '');
INSERT INTO model_code VALUES('HYPL', '펠리세이드', 'HY', '');
INSERT INTO model_code VALUES('HYIO', '아이오닉', 'HY', '');
INSERT INTO model_code VALUES('HYST', '스타리아', 'HY', '');
INSERT INTO model_code VALUES('GEG8', 'G80', 'GE', '');
INSERT INTO model_code VALUES('GEEQ', 'EQ900', 'GE', '');
INSERT INTO model_code VALUES('GEG7', 'G70', 'GE', '');
INSERT INTO model_code VALUES('GEG9', 'G90', 'GE', '');
INSERT INTO model_code VALUES('GEV8', 'GV80', 'GE', '');
INSERT INTO model_code VALUES('GEV7', 'GV70', 'GE', '');
INSERT INTO model_code VALUES('KIKV', '카니발', 'KI', '');
INSERT INTO model_code VALUES('KIK7', 'K7', 'KI', '');
INSERT INTO model_code VALUES('KIMN', '모닝', 'KI', '');
INSERT INTO model_code VALUES('KIK5', 'K5', 'KI', '');
INSERT INTO model_code VALUES('KISR', '쏘렌토', 'KI', '');
INSERT INTO model_code VALUES('KILY', '레이', 'KI', '');
INSERT INTO model_code VALUES('KISP', '스포티지', 'KI', '');
INSERT INTO model_code VALUES('KIK3', 'K3', 'KI', '');
INSERT INTO model_code VALUES('KIK9', 'K9', 'KI', '');
INSERT INTO model_code VALUES('KIK8', 'K8', 'KI', '');
INSERT INTO model_code VALUES('KIMV', '모하비', 'KI', '');
INSERT INTO model_code VALUES('KIST', '스팅어', 'KI', '');
INSERT INTO model_code VALUES('KISO', '쏘울', 'KI', '');
INSERT INTO model_code VALUES('KINR', '니로', 'KI', '');
INSERT INTO model_code VALUES('KISE', '셀토스', 'KI', '');
INSERT INTO model_code VALUES('CHSP', '스파크', 'CH', '');
INSERT INTO model_code VALUES('CHMA', '말리부', 'CH', '');
INSERT INTO model_code VALUES('CHCZ', '크루즈', 'CH', '');
INSERT INTO model_code VALUES('CHMT', '마티즈', 'CH', '');
INSERT INTO model_code VALUES('CHTV', '트레일블레이저', 'CH', '');
INSERT INTO model_code VALUES('CHCA', '카마로', 'CH', '');
INSERT INTO model_code VALUES('SAS5', 'SM5', 'SA', '');
INSERT INTO model_code VALUES('SAS6', 'SM6', 'SA', '');
INSERT INTO model_code VALUES('SAS3', 'SM3', 'SA', '');
INSERT INTO model_code VALUES('SAS7', 'SM7', 'SA', '');
INSERT INTO model_code VALUES('SAQ6', 'QM6', 'SA', '');
INSERT INTO model_code VALUES('SAQ3', 'QM3', 'SA', '');
INSERT INTO model_code VALUES('SAQ5', 'QM5', 'SA', '');
INSERT INTO model_code VALUES('SAX3', 'XM3', 'SA', '');
INSERT INTO model_code VALUES('SSKO', '코란도', 'SS', '');
INSERT INTO model_code VALUES('SSTV', '티볼리', 'SS', '');
INSERT INTO model_code VALUES('SSRX', '렉스턴', 'SS', '');
INSERT INTO model_code VALUES('BM5S', '5시리즈', 'BM', '');
INSERT INTO model_code VALUES('BM3S', '3시리즈', 'BM', '');
INSERT INTO model_code VALUES('BM7S', '7시리즈', 'BM', '');
INSERT INTO model_code VALUES('BMGT', '그란투리스모', 'BM', '');
INSERT INTO model_code VALUES('BMX5', 'X5', 'BM', '');
INSERT INTO model_code VALUES('BMX6', 'X6', 'BM', '');
INSERT INTO model_code VALUES('BM4S', '4시리즈', 'BM', '');
INSERT INTO model_code VALUES('BMX3', 'X3', 'BM', '');
INSERT INTO model_code VALUES('BMX4', 'X4', 'BM', '');
INSERT INTO model_code VALUES('BM6S', '6시리즈', 'BM', '');
INSERT INTO model_code VALUES('BMM5', 'M5', 'BM', '');
INSERT INTO model_code VALUES('BMZ4', 'Z4', 'BM', '');
INSERT INTO model_code VALUES('BZEC', 'E클래스', 'BZ', '');
INSERT INTO model_code VALUES('BZSC', 'S클래스', 'BZ', '');
INSERT INTO model_code VALUES('BZCC', 'C클래스', 'BZ', '');
INSERT INTO model_code VALUES('BZCS', 'CLS', 'BZ', '');
INSERT INTO model_code VALUES('BZGC', 'GLC', 'BZ', '');
INSERT INTO model_code VALUES('BZGE', 'GLE', 'BZ', '');
INSERT INTO model_code VALUES('BZAC', 'A클래스', 'BZ', '');
INSERT INTO model_code VALUES('BZCA', 'CLA', 'BZ', '');
INSERT INTO model_code VALUES('BZGA', 'GLA', 'BZ', '');
INSERT INTO model_code VALUES('BZGC', 'G클래스', 'BZ', '');
INSERT INTO model_code VALUES('BZGT', 'AMG GT', 'BZ', '');
INSERT INTO model_code VALUES('BZGS', 'GLS', 'BZ', '');
INSERT INTO model_code VALUES('AUA6', 'A6', 'AU', '');
INSERT INTO model_code VALUES('AUA4', 'A4', 'AU', '');
INSERT INTO model_code VALUES('AUA7', 'A7', 'AU', '');
INSERT INTO model_code VALUES('AUA8', 'A8', 'AU', '');
INSERT INTO model_code VALUES('AUA5', 'A5', 'AU', '');
INSERT INTO model_code VALUES('AUQ5', 'Q5', 'AU', '');
INSERT INTO model_code VALUES('AUQ7', 'Q7', 'AU', '');
INSERT INTO model_code VALUES('AUA3', 'A3', 'AU', '');
INSERT INTO model_code VALUES('AUQ3', 'Q3', 'AU', '');
INSERT INTO model_code VALUES('AUR8', 'R8', 'AU', '');
INSERT INTO model_code VALUES('TEM3', '모델3', 'TE', '');
INSERT INTO model_code VALUES('TEMS', '모델S', 'TE', '');
INSERT INTO model_code VALUES('TEMX', '모델X', 'TE', '');
INSERT INTO model_code VALUES('TEMY', '모델Y', 'TE', '');
INSERT INTO model_code VALUES('FXTG', '티구안', 'FX', '');
INSERT INTO model_code VALUES('FXPS', '파사트', 'FX', '');
INSERT INTO model_code VALUES('FXGF', '골프', 'FX', '');
INSERT INTO model_code VALUES('FXZT', '제타', 'FX', '');

--
