-- 공지사항 테이블 생성
CREATE TABLE NOTICE(
  id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL COMMENT '제목',
  content MEDIUMTEXT DEFAULT NULL COMMENT '내용',
  views INT NOT NULL COMMENT '조회수',
  reg_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  upt_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) AUTO_INCREMENT = 1000000000;

-- 문의 테이블 생성
CREATE TABLE QNA(
  id INT NOT NULL AUTO_INCREMENT,
  member_id INT NOT NULL,
  title VARCHAR(100) NOT NULL COMMENT '제목',
  content MEDIUMTEXT DEFAULT NULL COMMENT '내용',
  status VARCHAR(45) DEFAULT NULL,
  reg_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  upt_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (member_id) REFERENCES MEMBER (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) AUTO_INCREMENT = 1000000000;

-- 문의답변 테이블 생성
CREATE TABLE QNA_ANSWER(
  id INT NOT NULL AUTO_INCREMENT,
  qna_id INT NOT NULL,
  content MEDIUMTEXT DEFAULT NULL COMMENT '내용',
  reg_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (qna_id) REFERENCES QNA (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) AUTO_INCREMENT = 1000000000;

-- 자주묻는질문 테이블 생성
CREATE TABLE FAQ(
  id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL COMMENT '제목',
  content MEDIUMTEXT DEFAULT NULL COMMENT '내용',
  category VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (id)
) AUTO_INCREMENT = 1000000000;