-- 마스터코드(대분류) 테이블 생성: 보험옵션코드, 아이템옵션코드, 차량옵션코드
CREATE TABLE CODE_MASTER(
  code VARCHAR(20) NOT NULL,
  name VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (code)
);

-- 서브코드(중분류) 테이블 생성
CREATE TABLE CODE_SUB(
  code VARCHAR(20) NOT NULL,
  name VARCHAR(20) DEFAULT NULL,
  master_code VARCHAR(20) NOT NULL,
  PRIMARY KEY (code),
  FOREIGN KEY (master_code) REFERENCES CODE_MASTER (code) ON DELETE RESTRICT ON UPDATE RESTRICT
);

-- 차량브랜드코드 테이블 생성
CREATE TABLE CODE_BRAND(
  code VARCHAR(20) NOT NULL,
  name VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (code)
);

-- 차량모델코드 테이블 생성
CREATE TABLE CODE_MODEL(
  code VARCHAR(20) NOT NULL,
  name VARCHAR(20) DEFAULT NULL,
  img VARCHAR(500) DEFAULT NULL,
  brand_code VARCHAR(20) NOT NULL,
  PRIMARY KEY (code),
  FOREIGN KEY (brand_code) REFERENCES CODE_BRAND (code) ON DELETE RESTRICT ON UPDATE RESTRICT
);

-- 보험옵션코드 테이블 생성
CREATE TABLE CODE_INSURANCE_OPTION(
  code VARCHAR(20) NOT NULL,
  price INT DEFAULT NULL,
  car_id INT NOT NULL,
  PRIMARY KEY (code, car_id),
  FOREIGN KEY (car_id) REFERENCES CAR (id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

-- 업체보유캠핑도구옵션코드 테이블 생성
CREATE TABLE CODE_ITEM_OPTION(
  code VARCHAR(20) NOT NULL,
  company_id INT NOT NULL,
  PRIMARY KEY (code, company_id),
  FOREIGN KEY (company_id) REFERENCES COMPANY (id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

-- 차량옵션코드 테이블 생성
CREATE TABLE CODE_CAR_OPTION(
  code VARCHAR(20) NOT NULL,
  car_id INT NOT NULL,
  PRIMARY KEY (code, car_id),
  FOREIGN KEY (car_id) REFERENCES CAR (id) ON DELETE RESTRICT ON UPDATE RESTRICT
);