-- 업체 테이블 생성
CREATE TABLE COMPANY (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) DEFAULT NULL COMMENT '업체명',
  com_number VARCHAR(45) DEFAULT NULL COMMENT '사업자등록번호',
  tel VARCHAR(45) DEFAULT NULL,
  status VARCHAR(45) DEFAULT NULL,
  reg_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  upt_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  postal_code VARCHAR(45) DEFAULT NULL COMMENT '우편번호',
  address VARCHAR(45) DEFAULT NULL COMMENT '주소',
  member_id INT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (member_id) REFERENCES MEMBER (id) ON DELETE RESTRICT ON UPDATE RESTRICT
);