-- 견적요청 테이블 생성
CREATE TABLE ESTIMATE_REQUEST(
  id INT NOT NULL AUTO_INCREMENT,
  member_id INT NOT NULL,
  brand VARCHAR(45) DEFAULT NULL,
  model VARCHAR(45) DEFAULT NULL,
  options VARCHAR(45) DEFAULT NULL,
  items VARCHAR(45) DEFAULT NULL,
  start_date DATE COMMENT '예약시작일',
  end_date DATE COMMENT '예약만료일',
  reg_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  upt_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (member_id) REFERENCES MEMBER (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) AUTO_INCREMENT = 1000000000;

-- 제출견적 테이블 생성
CREATE TABLE ESTIMATE(
  id INT NOT NULL AUTO_INCREMENT,
  estimate_req_id INT NOT NULL,
  company_id INT NOT NULL,
  car_id INT NOT NULL,
  options VARCHAR(45) DEFAULT NULL,
  items VARCHAR(45) DEFAULT NULL,
  price INT DEFAULT NULL,
  memo VARCHAR(200) DEFAULT NULL,
  reg_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  upt_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (estimate_req_id) REFERENCES ESTIMATE_REQUEST (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY (company_id) REFERENCES COMPANY (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY (car_id) REFERENCES CAR (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) AUTO_INCREMENT = 1000000000;