-- 첨부파일 테이블 생성
CREATE TABLE FILE(
  id INT NOT NULL AUTO_INCREMENT,
  file_no VARCHAR(45) DEFAULT NULL COMMENT '파일번호',
  name VARCHAR(45) DEFAULT NULL COMMENT '파일명',
  org_name VARCHAR(45) DEFAULT NULL COMMENT '원본파일명',
  file_type VARCHAR(45) DEFAULT NULL COMMENT '파일유형',
  file_size VARCHAR(45) DEFAULT NULL COMMENT '파일크기',
  reg_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  upt_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  ref_post_code VARCHAR(45) NOT NULL COMMENT '관련게시글코드',
  ref_post_id INT NOT NULL COMMENT '관련게시글식별번호',
  PRIMARY KEY (id)
) AUTO_INCREMENT = 1000000000;