-- 회원 테이블 생성
CREATE TABLE member (
  id INT NOT NULL AUTO_INCREMENT,
  login_id VARCHAR(20) DEFAULT NULL,
  password VARCHAR(45) DEFAULT NULL,
  name VARCHAR(20) DEFAULT NULL,
  birth DATE DEFAULT NULL,
  email VARCHAR(45) DEFAULT NULL,
  phone VARCHAR(45) DEFAULT NULL,
  auth VARCHAR(10) DEFAULT NULL,
  status VARCHAR(10) DEFAULT NULL,
  reg_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  upt_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);