-- 회원 테이블 생성
CREATE TABLE MEMBER (
  id INT NOT NULL AUTO_INCREMENT,
  login_id VARCHAR(20) DEFAULT NULL,
  password VARCHAR(45) DEFAULT NULL,
  name VARCHAR(20) DEFAULT NULL,
  birth DATE DEFAULT NULL,
  email VARCHAR(45) DEFAULT NULL,
  phone VARCHAR(45) DEFAULT NULL,
  auth VARCHAR(10) DEFAULT NULL,
  status VARCHAR(10) DEFAULT NULL,
  reg_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  upt_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) AUTO_INCREMENT = 1000000000;

-- API 가입 회원 테이블 생성
CREATE TABLE MEMBER_SNS(
  id INT NOT NULL AUTO_INCREMENT,
  access_token VARCHAR(500) DEFAULT NULL COMMENT '토큰',
  member_id INT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (member_id) REFERENCES MEMBER (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) AUTO_INCREMENT = 1000000000;

-- 회원탈퇴관리 테이블 생성
CREATE TABLE MEMBER_DROP(
  id INT NOT NULL AUTO_INCREMENT,
  reason VARCHAR(45) DEFAULT NULL COMMENT '탈퇴사유',
  memo VARCHAR(200) DEFAULT NULL COMMENT '메모',
  member_id INT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (member_id) REFERENCES MEMBER (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) AUTO_INCREMENT = 1000000000;