-- 렌트정보 테이블 생성
CREATE TABLE RENT(
  id INT NOT NULL AUTO_INCREMENT,
  car_id INT NOT NULL,
  member_id INT NOT NULL,
  rent_type VARCHAR(45) DEFAULT NULL COMMENT '렌트유형',
  start_date DATE COMMENT '예약시작일',
  receive_date DATE COMMENT '수령일',
  return_date DATE COMMENT '반납일',
  end_date DATE COMMENT '예약만료일',
  estimate_id INT DEFAULT NULL,
  reserver VARCHAR(45) DEFAULT NULL COMMENT '예약자명',
  status VARCHAR(45) DEFAULT NULL,
  reg_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  upt_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (car_id) REFERENCES car (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY (member_id) REFERENCES MEMBER (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) AUTO_INCREMENT = 1000000000;

-- 결제정보 테이블 생성
CREATE TABLE PAYMENT(
  id INT NOT NULL AUTO_INCREMENT,
  rent_id INT NOT NULL,
  price INT DEFAULT NULL,
  merchant_uid VARCHAR(45) DEFAULT NULL COMMENT '주문번호',
  pay_method VARCHAR(45) DEFAULT NULL COMMENT '결제방식',
  PRIMARY KEY (id),
  FOREIGN KEY (rent_id) REFERENCES RENT (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) AUTO_INCREMENT = 1000000000;

-- 렌트후기 테이블 생성
CREATE TABLE RENT_REVIEW(
  id INT NOT NULL AUTO_INCREMENT,
  car_id INT NOT NULL,
  member_id INT NOT NULL,
  rent_id INT NOT NULL,
  title VARCHAR(100) NOT NULL COMMENT '제목',
  content VARCHAR(2000) DEFAULT NULL COMMENT '내용',
  score INT NOT NULL COMMENT '별점',
  reg_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  upt_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (car_id) REFERENCES CAR (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY (member_id) REFERENCES MEMBER (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY (rent_id) REFERENCES RENT (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) AUTO_INCREMENT = 1000000000;
